README.md

According to Telegram Bot API [recent changes](https://core.telegram.org/bots/api#recent-changes):
```
August 29, 2015
Added support for self-signed certificates: upload your certificate using the
certificate parameter in the setWebhook method.
```

Minor: self-signed certificates are now allowed

---

src/telegram.js
src/telegramPolling.js

Sometimes polling is dead, problem with network and other problems. 
It allow control polling via lastUpdate time  and manual restart polling.

lastUpdate && initPolling

---

README.md
src/telegram.js
test/index.js

```getFile``` method is not sufficient and a little bit useless (it can give you just a part of the file url)
```getFileLink``` should be much more useful
If you'd like to accept this PR, you should accept that PR first: https://github.com/yagop/node-telegram-bot-api/pull/32

Added getFileLink method

---

src/telegramPolling.js

fixes #20. thanks!!
by the way, i'm seeing a lot of tests fail locally due to `PEER_ID_INVALID`. it looks like i should probably set a `TEST_USER_ID`, but i'm not sure where to get that value from. thanks again

allow 0ms for polling interval

---

src/telegram.js

This sends the file as "My File.ext" instead of "My%20File.ext".

URL-decoded filename when sending file from stream

---

package.json
src/telegram.js
test/index.js

I've added the new methods from the updated Bots API in Telegram. This includes all of the methods for kicking/banning users as well.
The APIs for kicking and unbanning chat members don't seem to work right now because it says the bots must be admins in the groups, but there's no way to make bots admins in groups quite yet. (unless I'm missing something...)
EDIT: It seems that the developers are aware that users cannot make bots admins and are fixing it. Personally, I think they're trying a slow rollout.
- [`kickChatMember`](https://core.telegram.org/bots/api#kickchatmember)
- [`unbanChatMember`](https://core.telegram.org/bots/api#unbanchatmember)
- [`answerCallbackQuery`](https://core.telegram.org/bots/api#answercallbackquery)
- …

Update for Telegram Bots 2.0

---

src/telegramWebHook.js

For [writable streams](https://nodejs.org/api/stream.html#stream_class_stream_writable), like [http.ClientRequest](https://nodejs.org/api/http.html#http_class_http_clientrequest), there is no `end` event, only `finish`. Thus, `req.end` is never called and never sending a response.
This results in a nasty bug for WebHook users that basically renders the library useless because if Telegram doesn't receive a response from the bot server, it will continue to queue and send requests until it does, or until 24 hours have passed. This means, if you are responding to a message, your bot will send the response over and over and over until you either kill it or the 24 hours are up.

Fixes stream end event never being called

---

src/telegram.js
test/index.js

This pull request adds the method and test for sendVenue. This method was added to the Telegram Bot API on April 9, 2016 in the Bot API 2.0 update. See https://core.telegram.org/bots/api#sendvenue for more info.
I did this blindly in GitHub because the change seems simple enough. I did briefly test it live in my Telegram bot and it sent the venue correctly.
I attached a screenshot of how the venue looks in the iOS client:

add the sendVenue method

---

src/telegram.js
test/index.js

**Bug:**
The (private) method TelegramBot#_formatSendData(), used by public
methods, such as TelegramBot#sendPhoto(), throws an error
if the stream passed (fs.readStream) has the property 'path',
being an instance of Buffer.
For example,
```js
const stream = fs.createReadStream(Buffer.from('cat.png'));
Buffer.isBuffer(stream.path); // true
bot.sendPhoto(chatId, stream);
```
Would throw an error, like
```txt
TypeError: Path must be a string. Received <Buffer 60 62 63 64>
```
This is because of this line ([src/telegram.js:297](https://github.com/yagop/node-telegram-bot-api/blob/e0e5e9a7b0cbf823e008704b76d614e5da6e2922/src/telegram.js#L297)):
```js
fileName = URL.parse(path.basename(data.path)).pathname;
```
`path.basename()` can not handle buffer (non-string) paths. From the docs, ["A …

Fix handling fs.readStream.path if it's a buffer

---

README.hbs
README.md
src/telegram.js

Adds support for the `edited_message` parameter in Updates.
Emits an `edited_message` event when a message is edited, and also two specific events, `edited_message_text` and `edited_message_caption`, depending on the type of the message.

Add edited_message event

---

README.md
src/telegram.js

By default,  all regexes registered via `onText` are tried and in case of match callbacks are called, even if match is already found, which can cause one message to be processed multiple times.
I added `onlyFirstMatch` option which, as the name suggests, causes the bot to ignore further regexes after match is found.
It also enables people to add `.onText(/(?:)/, ...)` or something like that to handle the messages which were not matched by any regex.
I did not change existing behavior, you need to opt-in.
That's my first pull request, so I appreciate any hints you could give me.

Add option to ignore further regexes after match is found

---

package.json
src/telegram.js

I have a server which has only ipv6 access to api.telegram.org. So, I must pass `family: 6` option for each request to telegram api.
It would be great to add an extra option to TelegramBot constructor which makes it possible.
@yagop what do you think?

Proxy extra request options

---

README.hbs
README.md
src/telegram.js

bot will now get updates about posts in channels. Added new fields channel_post and edited_channel_post to Update.
[v2.3 Update](https://core.telegram.org/bots/api/#update)
Example:
```js
bot.on('channel_post', function (msg) {
var chatId = msg.chat.id;
console.log(msg.text)
bot.sendMessage(chatId, 'New Channel Post Detected');
});
bot.on('edited_channel_post', function (msg) {
var chatId = msg.chat.id;
bot.sendMessage(chatId, 'Channel Post Has Been Edited');
});
```

New Update Fields From API v2.3

---

README.md
src/telegram.js
test/telegram.js

See:
* deleteWebhook: https://core.telegram.org/bots/api#deletewebhook
* getWebhookInfo: https://core.telegram.org/bots/api#getwebhookinfo
---
Are we using a typo with the word **WebHook**?
|Bot API|Library|
|---|---|
|setWeb**h**ook|setWeb**H**ook|
|deleteWeb**h**ook|deleteWeb**H**ook|
|getWeb**h**ookInfo|getWeb**H**ookInfo|
If so, we should fix this typo by supporting **both**
Web**H**ook and Web**h**ook; thus ensuring backwards-compatibility
and consistency with how we have "taught" our community to
name it as.
On major release, we should consider dropping the Web**H**ook
for Web**h**ook!

Add deleteWebHook, getWebHookInfo

---

README.md

**Ref:** #260 
**Info:** Displays the Bot API version as a status badge.

Add Bot API Version Status Badge

---

doc/api.md
src/telegram.js
src/telegramWebHook.js
test/telegram.js
test/utils.js

Docker-ized environments usually expose an HTTP endpoint for health checks.
For example, in order to use a bot built with this lib in a kubernetes cluster, we have to give it an HTTP endpoint that responds 200 OK.
Refs:
https://github.com/kubernetes/contrib/tree/master/ingress/controllers/gce#health-checks
https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#defining-a-liveness-http-request

Webhook health check endpoint

---

CHANGELOG.md
doc/usage.md
src/errors.js
src/telegram.js
src/telegramPolling.js
src/telegramWebHook.js
test/telegram.js
test/utils.js

Add proper error handling. Please `doc/usage.md` for documentation on
error handling.
* Feature Request: https://github.com/yagop/node-telegram-bot-api/issues/114

src: Add proper error handling

---

src/telegram.js
test/telegram.js

Regex matching in `onText`: Resets the search index to start each regex match at the beginning again . 
**Note:** I usually add test cases to code I add/modif, but in this case it seems rather difficult to do that without modifying the `onText `function itself. I want to count the number of times the callback is executed. Any Ideas?
Issue #325

fix(onText): reset state of global regexp after search

---

README.md

I'd like to add RedBot (https://github.com/guidone/node-red-contrib-chatbot) to the list of projects using telegram-bot-api. Just updated the readme.md
Thanks
None

Add RedBot to list of projects using telegram-bot-api

---

doc/api.md
src/telegram.js
test/telegram.js

**sendVideoNote**
[[source](https://core.telegram.org/bots/api#sendvideonote)]
_There seems to be an issue with Telegrams documentation regarding this method, which doesn't state that length is actually a required parameter._

[API] v3 SendVideoNote method

---

doc/usage.md
src/telegram.js

[[source](https://core.telegram.org/bots/api#message)]
Added 6 missing message sub-types: `game`, `pinned_message`, `migrate_from_chat_id`, `migrate_to_chat_id`, `channel_chat_created`, `supergroup_chat_created`
Rename 1 message sub-type: `new_chat_members`

[Update] Message sub-types

---

src/telegram.js

Return valid path on Windows OS. 
closes #363
P.S. I didn't manage to run your tests because I have no idea how to get TEST_PROVIDER_TOKEN / TEST_GAME_SHORT_NAME / TEST_GROUP_ID
It would be nice to have a description how to get these in your docs :)

fixed download file path on windows

---

doc/api.md
src/telegram.js

**editMessageLiveLocation**
[[source](https://core.telegram.org/bots/api#editmessagelivelocation)]
**stopMessageLiveLocation**
[[source](https://core.telegram.org/bots/api#stopmessagelivelocation)]

[API v3.4] Support live locations

---

src/telegram.js

**setChatStickerSet**
[[source](https://core.telegram.org/bots/api#setchatstickerset)]
**deleteChatStickerSet**
[[source](https://core.telegram.org/bots/api#deletechatstickerset)]

[API v3.4] Support sticker sets

---

CHANGELOG.md
doc/api.md
doc/usage.md
src/telegram.js
src/telegramPolling.js

References:
* Issue #36: https://github.com/yagop/node-telegram-bot-api/issues/36
* answer/solution: https://github.com/yagop/node-telegram-bot-api/issues/36#issuecomment-268532067

src/polling: Fix the Offset Infinite Loop bug

---

doc/api.md
src/telegram.js

Fixed annotation mistake described in issue https://github.com/yagop/node-telegram-bot-api/issues/490

Fixed annotations for message id parameter

---

doc/api.md
src/telegram.js

Update the library with minor changes from the latest bot API update (v4.0 released on 26/07/2018).
Add new methods:
- **editMessageMedia**
- **sendAnimation**
Add new message types:
- **passport_data**
- **animation**
- #624
- [Update release notes from Telegram](https://core.telegram.org/bots/api#july-26-2018)

[API v4.0] Publish new methods and message types

---

src/telegram.js
test/telegram.js

Follow up update to #625
- Tests for both methods (sendAnimation, editMediaMessage) have been
added. editMediaMessage is nested under sendAnimation, hence both tests
are technically under a single block.
- Add an improvement/minor fix to the editMediaMessage method, where we
now stringify the first parameter (media) object interally within the
library. This allows the lib user to simply pass an object as the 1st
param without stringifying it.

[v4.0] Add tests and add minor improvement

---

src/telegram.js

Unable to catch steam error while file can not be download.
```js
bot.downloadFile(documentId, downloadsPath)
.then(() => {})
.catch(() => {
// Never reach when error
})
```

Fix catch error while file not able download

---

src/telegram.js

Send Animation requires an `animation` field instead of `document`.
https://core.telegram.org/bots/api#sendanimation

fix: send animation

---

src/telegram.js

Sometimes it can be handy to be able to remote all reply and text listeners. Also removes the burden of needing to track what listeners are registered so you can unregister them with `removeTextListeners`/`removeReplyListeners`. Instead you can just use `clearTextListeners`/`clearReplyListeners`.

Add methods to clear reply and text listeners

---

CHANGELOG.md
README.md
doc/api.md
package.json
src/telegram.js

Support Bot API v5.4: 
* Add method *approveChatJoinRequest()*
* Add method *declineChatJoinRequest()*
* Add support for new updates:
* *chat_join_request*
Fixes:
* Method *editMessageMedia()* (Now you can send local files)
* Telegram Bot API v5.4 - https://core.telegram.org/bots/api#november-5-2021https://core.telegram.org/bots/api#november-5-2021
Listen event "chat_join_request": 
```js
bot.on('chat_join_request', data => {
console.log("Join Request");
console.log(data);
});
```
Example `approveChatJoinRequest`:
```js
bot.on('chat_join_request', join_request => {
let chat_id = join_request.chat.id;
let user_id = join_request.from.id;
bot.approveChatJoinRequest(chat_id, user_id);
bot.sendMessage(chat_id, "Welcome " + join_request.from.first_name + ", invitation accepted")
})
```
Example …

Support for Telegram Bot API 5.4

---

CHANGELOG.md
doc/api.md
package.json
src/telegram.js
test/telegram.js

* Add method *setChatMenuButton()*
* Add method *getChatMenuButton()*
* Add method *setMyDefaultAdministratorRights()*
* Add method *getMyDefaultAdministratorRights()*
* Add method *answerWebAppQuery()*
* Renamed the fields voice_chat_scheduled, voice_chat_started, voice_chat_ended, and voice_chat_participants_invited to video_chat_scheduled, video_chat_started, video_chat_ended, and video_chat_participants_invited
Tests:
* answerWebAppQuery
* setChatMenuButton
* getChatMenuButton
* setMyDefaultAdministratorRights
* getMyDefaultAdministratorRights
Telegram Bot API 6.0
* Telegram Bot API 6.0 - https://core.telegram.org/bots/api/#april-16-2022

Support for Telegram Bot API 6.0

---

src/telegram.js

https://core.telegram.org/bots/api#setstickersetthumb
Now you can add thumb image to the sticker set

setStickerSetThumb function added

---

.eslintrc
CHANGELOG.md
doc/api.md
package.json
src/telegram.js
test/telegram.js

Remove legacy methods:
- getChatMembersCount
- kickChatMember
Docs: 
- Update the docs of functions
-  Order functions follow the Telegram bot API docs
Fix:
- addStickerToSet() -> Allow to send tgs_sticker + webm_sticker
- Remove mandatory param  “start_parameter” from sendInvoice, because actually is a optional param
New Test:
- deleteStickerFromSet
- setStickerPositionInSet

Hotfix: tests + modify order src/telegram + docs

---

src/telegram.js

Is needed to stringify some options related with send arrays of messageEntities as specified in the doc of Telegram.
Using same method as for replyMarkup with **_fixReplyMarkup**
There are three possible options fields wich need to be stringified. (**entities**, **caption_entities** and **explanation_entities**)
* Telegram Bot API - sendMessage (entities): https://core.telegram.org/bots/api#sendmessage
* Telegram Bot API - copyMessage (caption_entities): https://core.telegram.org/bots/api#copymessage
* Telegram Bot API - sendPoll (explanation_entities): https://core.telegram.org/bots/api#sendpoll

Parse entities when sending request

---

CHANGELOG.md
doc/api.md
package.json
src/telegram.js

Add the support for Telegram Bot API v6.4
Telegram Bot API - https://core.telegram.org/bots/api#december-30-2022
```js
bot.onText(/\/editGeneralForum/, (msg) => {
bot.editGeneralForumTopic(msg.chat.id, "The cave")
})
bot.onText(/\/closeGeneralForum/, (msg) => {
bot.closeGeneralForumTopic(msg.chat.id)
})
bot.onText(/\/reopenGeneralForum/, (msg) => {
bot.reopenGeneralForumTopic(msg.chat.id)
})
bot.onText(/\/hideGeneralForum/, (msg) => {
bot.hideGeneralForumTopic(msg.chat.id)
})
bot.onText(/\/unhideGeneralForum/, (msg) => {
bot.unhideGeneralForumTopic(msg.chat.id)
})
```

feat: Telegram Bot API 6.4 Support

---

doc/api.md
src/telegram.js

Fix the missing `"_by_<bot_username>"` in documentation of `createNewStickerSet`.
https://core.telegram.org/bots/api#createnewstickerset

Fix createNewStickerSet description

---

CHANGELOG.md
doc/api.md
src/telegram.js
test/telegram.js

Support Telegram Bot API 6.6
Support Telegram Bot API 6.7
* Telegram Bot API - https://core.telegram.org/bots/api#march-9-2023
* Telegram Bot API - https://core.telegram.org/bots/api#april-21-2023
Add Test:

feat: Telegram Bot API Support 6.6 + 6.7 [WIP]

---

doc/api.md
src/telegram.js

Add missing `setWebhook` `secret_token` parameter to the documentation

docs: update api.md for setWebHook (fix #1083)

---

doc/api.md
src/telegram.js

Fixed an error on calling `getUserChatBoosts`, when `message_id` was sent instead of `user_id`
Issue #1200
Telegram Bot API - getUserChatBoosts: https://core.telegram.org/bots/api#getuserchatboosts

Fixed getUserChatBoosts method

---

src/errors.js

FatalError does not provide enough context for understanding underlying issues.
Where available, attach the "causing" error to the FatalError to allow later inspection on `.cause` (see https://nodejs.org/api/errors.html#errorcause)
Serializing Error objects with `util.inspect()` recursively serializes `error.cause` if it is set and would allow better log messages in consuming applications.
I don't believe the existing approach of copying of the stack from the causing error is "least surprise" for consuming authors, but I do not yet understand reasons for why it is as is, or likelihood of breaking existing code.
Recent node versions introduced a bug (https://github.com/nodejs/node/issues/54359) in certain network configurations that is becoming more numerous triggering EFATAL errors. …

RFC: fix: FatalError set reference to causing error

---

doc/api.md
src/telegram.js

I have added the savePreparedInilneMessage from Telegram Bot API v8.0 for the issue #1243
* Issue #1243: https://github.com/yagop/node-telegram-bot-api/issues/1243
* Telegram Bot API - doc for feat: https://core.telegram.org/bots/api#savepreparedinlinemessage

Feat/1243 save prepared inline message v8.0
