yagop/node-telegram-bot-api

README.md, src/telegram.js, test/index.js
Adds `sendVoice` function from Telegram bot API documentation.
https://core.telegram.org/bots/api#sendvoice
=> sendVoice function

package.json, src/telegram.js
This should allow the use of Buffers alongside Streams and Files on _formatSendData method.
=> Add Buffer support to _formatSendData

src/telegram.js
For listening to the new events and for sending inline replies.
=> Added basic support for the new inline API

src/telegramPolling.js
Fix: If use switch between webHook or Polling you get an 409 (http://telegram.wiki/bots:boterrorcode) telegram error.
=> Fix: If use switch between webHook or Polling you get an 409 (http://telegram.wiki/bots:boterrorcode) telegram error. #116

README.md, src/telegram.js, src/telegramPolling.js, test/index.js
Added a stopPolling function which stops polling after the last polling request resolves.
=> Create a stop method #81

README.md, src/telegram.js, test/index.js
Hi! I added getChat method — https://core.telegram.org/bots/api#getchat
=> getChat method

README.md, src/telegram.js
Hi.
I've implemented a few new methods from the last update of the Telegram Bot API.
I hope you add this to the library :smile:
=> Implemented new methods from the API v2.1

package.json
updated request-promise package to eliminate memory leaks
=> fixed #207 

README.md, src/telegram.js
=> Added new methods sendVenue and sendContact 

README.hbs, README.md
=> Add simple example in README (PR #54)

src/telegram.js
Fixes: https://github.com/yagop/node-telegram-bot-api/issues/77
=> Fix request performance issue

CONTRIBUTING.md, LICENSE.md, README.md, doc/api.hbs, doc/api.md, doc/help.md, doc/usage.md
* Add note about events in `api.md`
* Update copyright year
* Cleanup docs
https://github.com/yagop/node-telegram-bot-api/issues/289
=> Docs improvements

examples/expressWebhook.js
A webhook integration with an express app.
References:
* Issue #282 by @kamikazechaser
=> [Example] Express webhook

index.js, test/telegram.js
[x] All tests pass
[ ] I have run `npm run gen-doc`
Load transpiled code for node 5 to fix issue #297
* Issue #297: https://github.com/yagop/node-telegram-bot-api/issues/297
=> Load transpiled code for node 5

doc/usage.md, src/telegram.js
**New Update & Message types**
[[source](https://core.telegram.org/bots/api#update)]
[[source](https://core.telegram.org/bots/api#message)]
Added 2 new update types: `shipping_query`, `pre_checkout_query`
Added 2 new message sub-types: `successful_payment`, `invoice`
=> [API] v3 New update types and message sub-types

.vscode/settings.json, doc/api.md, src/telegram.js, test/README.md, test/telegram.js
**sendInvoice**
[[source](https://core.telegram.org/bots/api#sendinvoice)]
**answerShippingQuery**
[[source](https://core.telegram.org/bots/api#answershippingquery)]
**answerPreCheckoutQuery**
[[source](https://core.telegram.org/bots/api#answerprecheckoutquery)]
=> [API] v3 Payments

README.md
=> [Update] API version

doc/tutorials.md
=> Add tutorial link RUS

doc/tutorials.md
=> Persian Language added

src/telegram.js
Fix issue #448 with `answerShippingQuery`. The problem was, that `shipping_options` doesn't converting to JSON from array
* Issue #448
=> Fix issue with answerShippingQuery

doc/tutorials.md
Youtube playlist tutorial about building Telegram bot using node-telegram-bot-api [RUS]
=> One more tutorial ;) [RUS]

README.md
=> doc: Add missing full stop

doc/tutorials.md
Add tutorial article link that I wrote in Japanese website
- [Node.jsでTelegramのチャットボットを作る](https://qiita.com/neetshin/items/0e2f6fa3ade41adb77bc)
=> Update tutorial articles link

doc/tutorials.md
=> Add tutorial [ES]

README.md
I've added my keyboard wrapper to the community section of Readme.md
=> Added telegram-keyboard-wrapper to the community section

doc/api.md
=> doc: fix typo

doc/tutorials.md
using your module the bot can send sms templates
=> one more tutorial for node-telegram-bot-api

LICENSE.md, README.md
=> Copyright Updated

README.md
I've created this utility library for bots, that uses this library to show usage example. 😊
=> Added node-telegram-operation-manager to community field

CHANGELOG.md, doc/api.md, doc/usage.md, src/telegram.js
Update the library with minor changes from the latest bot API update (v4.2 released on 26/07/2018).
Add new methods:
- **sendPoll**
- **stopPoll**
Add new message type:
- **poll**
Add new update type:
- **poll**
- #718 
- [Update release notes from Telegram](https://core.telegram.org/bots/api#april-14-2019)
=> [API v4.2] Publish new methods, message and update types

CHANGELOG.md, LICENSE.md, README.md, package.json
As per #738, this library has not been pushed to npmjs for about 2 years now.
**Checklist**
~Update readme.md~ (Work on new PR)
~Update travis tests~ (Use separate branch)
~Update outdated/ security critical packages~ (Use separate branch)
=> [Package] Bump to v.0.40.0

examples/webhook/express.js
Use the built-in JSON parser middleware of Express.
See also: https://stackoverflow.com/questions/47232187/express-json-vs-bodyparser-json/47232318
=> bodyParser is built-in again.

src/telegram.js
Download file reuqest unable to use agent options
=> src/telegram: Add request options in getFileStream

doc/api.md, src/telegram.js
Fix bug with compare two regexp
```javascript
/123/ === /123/ // false
String(/123/) === String(/123/) // true
```
=> fix regexp compare

package.json
Related to https://github.com/advisories/GHSA-pp7h-53gx-mx7r
Update the version of "bl".
There is a security advisory about it: https://github.com/advisories/GHSA-pp7h-53gx-mx7r
=> Update bl minimum version

doc/tutorials.md
It's a guide to help new people how to set webhooks and test their bots using local server.
=> How to set webhooks using express local server and NGROK

CHANGELOG.md, README.md, doc/api.md, package.json, src/telegram.js, test/telegram.js
Support Bot API v5.5:
* Add method *banChatSenderChat()*
* Add method *unbanChatSenderChat()*
Fixes:
* Tests for support with new invite link format
* Telegram Bot API -> https://core.telegram.org/bots/api#december-7-2021
=> Telegram Bot API 5.5 Support

doc/usage.md
Added documentation related to events that was outdated.
Started this PR because of this issue: [here](https://github.com/yagop/node-telegram-bot-api/issues/927)
<!--
Add references to other documents/pages that are relevant to this
PR, such as related issues, documentation, etc.
* Telegram Bot API DOC - Getting updates: https://core.telegram.org/bots/api#getting-updates
=> doc: added missing documentation related to events

CHANGELOG.md, README.md, doc/api.md, src/telegram.js, test/telegram.js
Telegram Bot API v6.2
https://core.telegram.org/bots/api#august-12-2022
=> feat: Support Bot API v6.2

README.md
`@types/*` usually used for development (compile time) only, so I think it should put in `devDependencies`.
=> docs: update @types install note

CHANGELOG.md, README.md, doc/api.md, package.json, src/telegram.js, test/telegram.js
Add the support for Telegram Bot API v6.3
* Telegram Bot API - [Getting updates: https://core.telegram.org/bots/api#getting-updates](https://core.telegram.org/bots/api#november-5-2022)
Use example: 
```js
bot.onText(/\/opentopic/, (msg) => {
console.log("opentopic", msg)
if (msg?.is_topic_message) { // Check if the message is from a chat forum (topic)
bot.createForumTopic(msg.chat.id, "Test topic")
}
})
bot.onText(/\/closeTopic/, (msg) => {
if (msg?.is_topic_message) {
bot.closeForumTopic(msg.chat.id, msg.message_thread_id)
}
})
bot.onText(/\/reopenForumTopic/, (msg) => {
if (msg?.is_topic_message) {
bot.reopenForumTopic(msg.chat.id, msg.message_thread_id)
}
})
bot.onText(/\/deleteForumTopic/, (msg) => {
if (msg?.is_topic_message) {
bot.deleteForumTopic(msg.chat.id, msg.message_thread_id) …
```
=> feat: Telegram Bot API v6.3

README.md
It was also necessary to change the link in the document
=> docs: Update group link

doc/api.md, src/telegram.js
=> feat: copy messages

doc/api.md, src/telegram.js, test/telegram.js
=> Support for ReplyParameters and 3 methods of API 7.0
